config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'home#index'
  
  resources :boards do
    collection do
      get :my
    end
    resources :cards do
      member do
        patch :solve 
        get :solve, to: 'cards#show'
      end
      resources :comments, only: [:create]
    end 
  end


  resources :profiles, only: [:show]
  resources :cards, only: [:index] ,to: 'cards#list'

  resources :cards, only: [:index], to: 'cards#list'

  resources :records, only: [:show]
  
end

app/models/board.rb
class Board < ApplicationRecord
  #acts_as_paranoid

  has_many :cards, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :language, presence: true

  before_update :prevent_language_changed!
  before_destroy :check_before_modify!

  def self.search_by_title(search_term)
    if search_term
      where("LOWER(boards.title) LIKE :search_term",
      search_term: "%#{search_term.downcase}%")
    else
      all
    end
  end

  def editor_mode
    case self.language
      when "Ruby"
        "ace/mode/ruby"
      when "Python"
        "ace/mode/python"
      when "JavaScript"
        "ace/mode/javascript"
    end
  end

  def has_records?
    self.cards.map { |card| card.records.exists? }.include?(true)
  end

  private
  def check_before_modify!
    if has_records?
      errors.add :base, "很抱歉！已有答題紀錄，無法進行題組修改"
      throw(:abort)
    else
      self.cards.each do |card|
        card.destroy
      end
    end
  end

  def prevent_language_changed!
    if has_records? && change_language?
      errors.add :base, "很抱歉！已有答題紀錄，無法更改題組的程式語言"
      throw(:abort)
    end
  end

  def change_language?
    self.changed_attributes.include?(:language)
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :authenticate_user!, only: [:my, :new, :edit, :update, :destroy]
  before_action :find_board, only: [:show, :edit, :update, :destroy]
  before_action :build_board, only: [:new, :create]
  before_action :check_authority, only: [:edit, :update, :destroy]

  def index
    @q = Board.joins(:cards).distinct('boards.id').ransack(params[:q])
    @boards = @q.result
                .page(params[:page]).per(6)
  end
  
  def new
  end

  def create
    @board.assign_attributes(board_params)

    if @board.save
      redirect_to board_path(@board.id), notice: '新增成功！'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def my
    @board = current_user.boards
    redirect_to new_board_path if @board.count == 0
  end

  def update
    if @board.update(board_params)
      redirect_to my_boards_path, notice: '更新成功！'
    else
      render :edit
    end
  end

  def destroy
    if @board.destroy
      redirect_to my_boards_path, notice: '刪除成功！'
    else
      redirect_to my_boards_path, alert: '已有解題紀錄，刪除失敗！'
    end
  end

  private
  def check_authority
    redirect_to board_path(id: @board.id), notice: '權限不足，您不是擁有者' if @board.user_id != current_user.id
  end
  
  def find_board
    @board = Board.find(params[:id])
  end

  def build_board
    @board = current_user.boards.new
  end

  def board_params
    params.require(:board).permit(:title, :description, :language)
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with model: @board, local: true do |f| %>

  <% if @board.errors.any? %>
    <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <div id="board" class="bg-white w-4/5 xl:w-1/3 m-auto shadow rounded-lg border mt-10">

    <div id="board-head" class="border-b">
      <h1 class="border-gray-800 text-gray-700 font-bold text-xl text-center py-4">
        <%="題組"%>
      </h1>
    </div>

    <div id="board-body" class="p-10">
      <div class="flex my-6">
        <%= f.label :language, '語言',class: 'text-m text-gray-600' %>
        <%= f.select :language, [['Ruby','Ruby'],['JavaScript','JavaScript'],['Python','Python']],{}, 
                      class: 'w-3/5 shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline',
                      style: 'text-align-last: center; width: 100%'%>
      </div>

      <div class="flex my-6">
        <%= f.label :title, '名稱', class: 'text-m text-gray-600'%>
        <%= f.text_field :title, class: 'w-3/5 shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'%>
      </div>

      <div class="flex my-6">
        <%= f.label :description, '簡介', class: 'text-gray-600' %>
        <%= f.text_area :description, class: ' shadow border rounded text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
    </div>

    <div id="board-foot">
      <div class="flex my-6 pt-5 border-t">
        <%= f.submit '送出', class: 'w-1/3 m-auto bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'  %>
      <div>
    </div>

  </div>
<% end %>

app/views/boards/_index_tab.html.erb
<div id="tab-board-index" class=" w-full">
  <ul class="flex w-full mb-6">
    <li class="w-1/2 text-center block text-xl text-blue-600 bg-gray-100">
      <%= link_to(boards_path, 
                  :class => "#{'active' if current_path_last_string=="boards"} rounded-tl block py-5 text-l bg-gray-200 text-blue-600") do %>
                  探索題組
      <% end %>
    </li>
    <li class="w-1/2  text-center block text-xl text-blue-600 bg-gray-100">
      <%= link_to( cards_path, 
                  :class => "#{'active' if current_path_last_string=="cards"} rounded-tr block py-5 text-l bg-gray-200 text-blue-600") do %>
                  總覽題目
      <% end %>
    </li>
  </ul>
</div>

app/views/boards/edit.html.erb
<div id="board-edit" class="container-full">
  <%= render "boards/form" %>
</div>

app/views/boards/index.html.erb
<div class="container lg mx-auto my-12 px-4 md:px-12">
  <div class="flex flex-col">
    <div class="bg-white align-middle block min-w-full shadow overflow-hidden sm:rounded-lg ">
      <%= render "boards/index_tab" %>
      <nav class="mb-3">
        <%= search_form_for @q do |f| %>
        <div class="max-w-7xl mx-auto px-2 sm:px-4 lg:px-8">
          <div class="flex justify-between items-center h-16 ">
            <div class="flex-shrink-0 flex items-center">
              <div class="relative  border-none">
                <%= f.select :language_cont,
                  [["請選擇語言", ""], ["Ruby", "ruby"], ["Javascript", "javascript"], ["Python", "python"]], 
                  {}, 
                  {
                    class: 'bg-white text-blue-500 appearance-none border inline-block py-3 pl-3 pr-8 rounded leading-tight w-full text-sm',
                    id: "language"
                  }
                %>
                <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2">
                  <%= render_svg 'icons/chevron-down' %>
                </div>      
              </div>
            </div>
            <div class="sm:block  lg:flex-shrink-0 flex justify-end rounded-lg">         
              <div class="pt-2 relative mx-auto text-gray-600">
                <%= f.search_field :title_cont, class: "border-2 border-gray-300 bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none" ,placeholder: "搜尋 ..."%>
                <button type="submit" class="absolute right-0 top-0 mt-5 mr-4">
                  <%= render_svg 'icons/search'%>
                </button>
              </div> 
            </div>
          </div>
        </div>
        <% end %>
      </nav>
      <hr>
      <div class="my-5 mx-5 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <% @boards.each do |board| %>
          <%= link_to board_path(board.id), class: 'bg-white overflow-hidden shadow rounded-lg hover:shadow-lg hover:bg-gray-400' do %>
            <div class="bg-white border border-gray-200 px-4 py-5 sm:p-6">
              <dl>
                <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium leading-5 bg-<%= language_color(board.language) %>-100 text-<%= language_color(board.language) %>-800">
                  <%= board.language %>
                </span>
                
                <dt class="flex justify-start my-4 text-xl leading-5 font-medium text-blue-800 font-bold truncate">
                  <%= board.title %>
                </dt>
                <hr>
                <p class="my-4 text-gray-500 h-12 overflow-hidden"><%= board.description %></p>
                <hr>
                <dd class="flex justify-between items-center mt-5">
                  <div class="flex">
                    <span class="inline-block h-6 w-6 rounded-full overflow-hidden bg-gray-100">
                      <svg class="h-full w-full text-gray-500" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
                      </svg>
                    </span>
                    <div class="text-xl leading-8 font-semibold text-gray-900">
                      <p class="flex items-baseline text-sm">
                        <%= email_account(board.user) %>
                      </p>
                    </div>
                  </div>
                  <div class="flex items-baseline">
                    <div class="text-sm leading-5 font-semibold text-blue-600">
                      <%= board.cards.count%>題
                    </div>
                  </div>
                </dd>
              </dl>
            </div>
          <% end %>
        <% end %>
      </div>
      <hr>
      <nav class="bg-white px-4 py-3 flex items-center justify-between sm:px-6 sm:justify-end">
        <div class="flex-1 flex justify-between sm:justify-end">
          <%= link_to_prev_page @boards, '上一頁', class: 'relative inline-flex items-center px-4 py-2 border border-blue-300 text-sm leading-5 font-medium rounded-lg text-blue-700 bg-white hover:text-blue-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-blue-100 active:text-blue-700 transition ease-in-out duration-150' %>
          <%= link_to_next_page @boards, '下一頁', class: 'relative inline-flex items-center px-4 py-2 border border-blue-300 text-sm leading-5 font-medium rounded-lg text-blue-700 bg-white hover:text-blue-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-blue-100 active:text-blue-700 transition ease-in-out duration-150' %>
        </div>
      </nav>
    </div>
  </div>
</div>

<script>
  $('#language').on('change', function(){
    $('#board_search').submit()
  })
</script>

app/views/boards/my.html.erb
<div id="my-board" class="w-5/6 xl:w-3/5 m-auto rounded-lg mt-10">

  <div id="my-board-head" class="border-b">
    <h1 class="mb-5 text-gray-900 font-bold inline-block">所有題組</h1>

    <p class="mb-6 inline-block float-right">
      <%= link_to(new_board_path, 
                  :class => 'bg-blue-500 hover:bg-blue-700 text-white py-2 px-3 rounded') do %>
        <span class="font-bold">
          <i class="fa fa-plus mr-2"></i>題組
        </span>
      <% end %>
    </p>

  </div>
  
  <div id="my-board-body" class="pl-4 py-6">
    <% order = 1 %>
    <% @board.each do |board| %>
      <div class="my-4 rounded">
      
        <div class="-mt-2 -ml-2 relative -mb-10">
          <span class="bg-gray-600 text-white py-1 px-2 text-xs text-right">
            <%= board.language%>
          </span>
        </div>

        <div class="one-board bg-white flex border shadow my-4 rounded">
          <div class="w-24 text-lg self-center">
            <span class="w-full h-full text-center inline-block">
              <%= order %>
            </span>
          </div>
            
          <div class="w-full ml-8 ">

            <div class="w-full flex">
              <div class="w-full mt-1">
                <%= link_to(new_board_card_path(board.id), 
                            :class => 'pt-5 pb-1 block w-full text-blue-700 hover:text-blue-600 font-bold text-xl') do %>
                  <span class="-ml-8 mr-2">
                    <i class="fa fa-book"></i>
                  </span>
                  <span><%= board.title %></span>
                  <span class="text-xs text-gray-600"> - <%= board.cards.length %> 題</span>
                <% end %>
              </div>
            </div>
                        
            <div class="w-full mb-6">
              <p class="text-gray-600 text-sm leading-relaxed">
                <%= board.description%>
              </p>
            </div>
            
          </div>

          <div class="part-btns hover w-1/6 text-right pr-5 mt-6">
            <%= link_to(edit_board_path(board.id), 
                        :class => 'w-2 text-gray-500 hover:text-gray-700 text-white py-1 mr-1') do %>
              <i class="btn-edit fa fa-pencil  text-2xl"></i>
            <% end %>
            <%= link_to(board_path(board.id),method: 'delete',data: {confirm: 'Are you sure ?!'}, 
                        :class => 'w-2 text-gray-500 hover:text-gray-700 text-white py-1 rounded mr-1') do %>
              <i class="btn-del fa fa-times text-2xl"></i>
            <% end %>
          </div>

        </div>
      </div>
      <% order = order + 1 %>
    <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<div id="board-new" class="container-full">
  <%= render "boards/form" %>
</div>

app/views/boards/show.html.erb
<div id="page-board-list" class="container-full bg-white px-6 py-4">

  <div id="part-borard-info" class="w-full">
    <%= render "cards/banner_board_info" %>
  </div>

  <div class="flex w-full">

    <div id="part-cards-list" class="w-full m-auto m-0 pb-12">
      <%= render "cards/nav_cards_list", nowCard: ''  %>
    </div>

  </div>

</div>