config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'home#index'
  
  resources :boards do
    collection do
      get :my
    end
    resources :cards do
      member do
        patch :solve 
        get :solve, to: 'cards#show'
      end
      resources :comments, only: [:create]
    end 
  end


  resources :profiles, only: [:show]
  resources :cards, only: [:index] ,to: 'cards#list'

  resources :cards, only: [:index], to: 'cards#list'

  resources :records, only: [:show]
  
end

app/models/card.rb
class Card < ApplicationRecord
  TAGS = %w[Algorithms Arrays Bionary Data_Structures Strings Symbol Hash Object Numbers Rules Loops Utilities Mathematics Methods While If...else Lists Each].freeze

  belongs_to :board
  has_many :records
  has_many :user, through: :records
  validates :title, presence: true
  validates :level, presence: true
  validates :result, presence: true

  before_update :check_before_modify!
  before_destroy :check_before_modify!

  def self.search_by(search_term)
    if search_term
      where("LOWER(title) LIKE :search_term",
      search_term: "%#{search_term.downcase}%")
    else
      all
    end
  end

  def has_records?
    self.records.exists?
  end

  private
  def check_before_modify!
    if has_records?
      errors.add :base, "很抱歉！已有答題紀錄，您無法進行題目修改"
      throw(:abort)
    end
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  before_action :find_board, except: [:list]
  before_action :find_card, only: [:edit, :show, :update, :destroy, :solve]
  before_action :build_card, only: [:index, :new, :create]
  before_action :get_code, only: [:create, :update]
  before_action :docker_exec_service, only: [:create, :update, :solve]
  before_action :exec_and_get_result, only: [:create, :update]

  before_action :check_authority, only: [:new, :edit, :update, :destroy]

  def index
    redirect_to new_board_card_path
  end

  def list
    @q = Card.ransack(params[:q])
    @cards = @q.result
               .includes(:board)
               .page(params[:page]).per(10)
  end
  
  def new
    @options = Card::TAGS
    @card.assign_attributes(test_code: [''], hints: [''])
  end

  def create
    @options = Card::TAGS
    if @docker_exec_service.fail?
      error_message
      attr_params = card_params.merge(result: @result)
      @card.assign_attributes(attr_params)
      return render :new
    else
      attr_params = card_params.merge(result: save_type(@result))
      @card.assign_attributes(attr_params)
      if params[:commit] == "送出" && @card.save
        redirect_to board_card_path(board_id: @board.id, id: @card.id), notice: '成功建立題目！'
      else
        render :new
      end
    end
  end

  def edit
    @options = Card::TAGS
  end

  def update
    @options = Card::TAGS
    if @docker_exec_service.fail?
      error_message
      attr_params = card_params.merge(result: @result)
      @card.assign_attributes(attr_params)
      return render :edit
    else
      attr_params = card_params.merge(result: save_type(@result))
      @card.assign_attributes(attr_params)
      if params[:commit] == "送出" && @card.update(attr_params)
        redirect_to board_card_path(board_id: @board.id, id: @card.id), notice: '成功修改題目！'
      else
        render :edit
      end
    end
  end

  def destroy
    if @card.destroy
      @board.cards.order(:updated_at).each_with_index do |card, idx|
        cur_order = idx + 1
        card.update(order: cur_order) if card.order != cur_order 
      end
      redirect_to board_path(@board), notice: '刪除成功！'
    else
      redirect_to board_path(@board), alert: '已有解題紀錄，刪除失敗！'
    end
  end

  def show
    @solved_records = @card.records.with_solved
    if @board.user == current_user
      render 'card_questioner'      
    else
      if current_user.present?
        @record = @card.records.find_by(user_id: current_user.id)
        if @record.present? && @record.solved
          render 'card_solved'
        else
          render_new_solving
        end  
      else
        render_new_solving
      end
    end
  end

  def solve
    @solved_cards = @card.records.with_solved
    @test_code = [@card.test_code[0]]
    @docker_exec_service.code = params[:record][:code]
    @docker_exec_service.test_code = @card.test_code
    exec_and_get_result
    error_message if @docker_exec_service.fail?

    @record = @card.records.find_by(user_id: current_user.id)
    if @record.nil?
      @record = current_user.records.new(card_id: @card.id, code: @card.default_code)
    end
    @record.assign_attributes(record_params)

    if params[:commit] == "送出"
      comparer_service
      @comparer_service.criteria = compare_type(@card.result)
      @comparer_service.value = @result
      
      @record.solved = @comparer_service.run
      @record.save
      
      if @record.solved
        flash[:notice] = "恭喜答對！"
        redirect_to board_card_path
      else
        print_true
        flash[:alert] = "錯誤！尚有 #{@comparer_service.result.count(false)} 筆測資未通過"
        render 'card_solving'
      end
    else
      @result = [@result&.first]
      render 'card_solving'
    end 
  end

  private
  def error_message
    if @docker_exec_service.timeout?
      flash[:alert] = "Timeout!"
    elsif @docker_exec_service.result.nil?
      flash[:alert] = "解答 / 測試資料 請勿空白"
    else
      @error, @result = @result, ""
    end
  end

  def docker_exec_service
    @docker_exec_service ||= (
      case @board.language
      when "Ruby"
        DockerExec::RubyService
      when "JavaScript"
        DockerExec::JsService
      when "Python"
        DockerExec::PythonService
      end
    ).new(@code, @test_code)
  end

  def exec_and_get_result
    @docker_exec_service.run
    @result = @docker_exec_service.result
  end

  def get_code
    @code = params[:card][:answer]
    @test_code = params[:card][:test_code]
  end

  def comparer_service
    @comparer_service ||= Comparer.new(@criteria, @value) 
  end

  def print_true
    if @comparer_service.index <= 0
      @test_code = [@card.test_code[0]]
      @result = [@result&.first]
    else
      @result = [*0..@comparer_service.index].map{ |e|
        @result[e]
      }
      @test_code = [*0..@comparer_service.index].map{ |e|
        @card.test_code[e]
      }
    end
  end

  def check_authority
    redirect_to board_path(id: @board.id), alert: 'check authority error! not owner!' if @board.user_id != current_user.id
  end

  def render_new_solving
    @record = Record.new(card_id: @card.id, code: @card.default_code)
    @test_code = [@card.test_code[0]]
    render 'card_solving'
  end

  def save_type(raw)
    raw.map{ |e| JSON.generate(e) }
  end

  def compare_type(raw)
    raw.map{ |e| JSON.parse(e) }
  end

  def card_params
    params.require(:card).permit(:title,
                                 :description,
                                 :default_code,
                                 :answer,
                                 :level,
                                 :order,
                                 :board_id,
                                {:tags=>[]},
                                 :result=>[],
                                 :hints=>[],
                                 :test_code=>[])
  end

  def record_params
    params.require(:record).permit(:code)
  end

  def find_board
    @board = Board.find(params[:board_id])
  end

  def find_card
    @card = @board.cards.find(params[:id])
  end

  def build_card
    @card = @board.cards.new
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_banner_board_info.html.erb
<div id="part-board" class="border-b py-4">

  <div class="one-board relative rounded px-4">

    <div class="flex"">
      <div class="flex-grow -ml-8 -mt-1">
        <span class="bg-gray-600 text-white py-1 px-2 text-s text-right">
          <%= @board.language%>
        </span>
      </div>
      <% if user_authority ==  "author" %>
        <div class="w-auto part-btns hover text-right w-auto">
            <%= link_to(edit_board_path(@board.id), 
                        :class => 'w-2 text-gray-500 hover:text-gray-700 text-white py-1 mr-1') do %>
              <i class="btn-edit fa fa-pencil  text-2xl"></i>
            <% end %>
            <span class=" <%="not-allowed" if @board.has_records? %>">
              <%= link_to(board_path(@board.id),method: 'delete',data: {confirm: 'Are you sure ?!'}, 
                          :class => 'w-2 text-gray-500 hover:text-gray-700 text-white py-1 rounded mr-1') do %>
                <i class="btn-del fa fa-times text-2xl"></i>
            <span>
            <% end %>
        </div>
      <% end %>
    </div>



      

    <div class="w-full ml-4 px-4">

      <div class="w-full flex">

        <div class="w-full mt-1 flex">
          <div class="flex-grow">
            <p class="block w-full text-blue-700 font-bold text-xl">
              <span class="-ml-8 mr-2">
                <i class="fa fa-book"></i>
              </span>
              <%= link_to(board_path(@board.id), :class => '') do %>
                <span><%= @board.title %></span>
              <% end %>
            </p>
          </div>
          
        </div>
      </div>

      <div class="w-full mb-2">

        <p class="text-gray-600 text-xs leading-relaxed">
          <% if @board.description %>
            <%= @board.description%>
          <% end %>
        </p>


      </div>

    </div>
    <div class="flex">
      <div class="flex-grow m-auto pl-8">
        <p class="text-xs text-gray-600 mt-2">
          <% if @board.cards.length %>
            <span class=" inline-block text-gray-600 mr-6">
              <%  cards_length = @board.cards.length %>
              <% if action_name=="new" %>
                <%  cards_length = @board.cards.length - 1 %>
              <% end %>
              共 <%= cards_length %> 題
            </span>
            <span class="">
              <%= link_to profile_path(@board.user) do %>
                  <%= email_account(@board.user)%>
              <% end %>
            </span>
          <% end %>
        </p>
      </div>

      <% if user_authority ==  "author" %>
        <div class="w-auto">
            <p class="inline-block text-right my-4 block whitespace-no-wrap">
              <%= link_to(new_board_card_path(@board.id), 
                          :class => 'bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded') do %>
                <span class="font-bold">
                  <i class="fa fa-plus mr-2"></i>題目
                </span>
              <% end %>
            </p>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/cards/_card_questioner.html.erb
<p class="absolute right-0 text-xs text-gray-600">//出題者-檢視頁//</p>


<div class="flex container">
  
  <div class="part-slider w-1/4 border-r">
    <%= render "cards/nav_cards_list", nowCard: @card.id %>
  </div>

  <div class="part-card px-4 w-3/4">

    <%= form_with model: @card, url: board_cards_path , local: true do |f| %>

      <div class="shadow border rounded  py-3 my-3">

        <div class="mg-0 leading-loose border-b">
          <h1 class="text-gray-900 font-bold text-2xl border-b px-2">
            <span class="mr-1"><%= @card.order %>  </span><%= @card.title %>
          </h1>
        </div>

        <div class="py-3 px-5">
          <p>
            <span class="inline-block border-grap-700 text-grap-900 px-2 py-1 border rounded text-sm text-white bg-orange-700">
              <%= @card.level %>
            </span>    
              

               <% if @card.tags %>
                <%  @card.tags.each do |tag| %>
                  <span class="inline-block border-grap-700 text-grap-900 px-2 py-1 border rounded text-sm text-white bg-gray-700">
                    <%= tag %>
                  </span>    
                <% end %>
              <% end %>


            </span>    
          </p>
        </div>

        <div class=" px-4 py-1 my-4">
          <section><%= @card.description %></section>
          <hr/>
          <div id="section-hints" class="">

            <% if @card.hints %>
              <span class="py-2 my-5">提示(<%= @card.hints.length %>):</span> 
              <ul>
                <% @card.hints.each do |hints| %>
                  <li class="hint"><%= hints %></li>
                <% end %>
              </ul>
            <% else %>

              <span class="cursor-not-allowed text-gray-500 py-2 px-3 my-5">(無提示)</span> 
            <% end %>
          </div>
        </div>
      </div>

      <div class="shadow border rounded my-5">

        <div class="mg-0 leading-loose border-b">
          <%= f.label :code, '預設程式碼', class: 'block w-100 px-5 text-gray-600'%>
        </div>

        <div class="px-4 py-1 my-4">
          <%= f.hidden_field :default_code, id: "default_code" %>
          <div class="editor readonly" data-target="default_code"></div>
        </div>

      </div>

      <div class="shadow border rounded my-5">
        <div class="mg-0 leading-loose border-b">
          <%= f.label :answer, '出題者解答', class: 'block w-100 px-5 text-gray-600'%>
        </div>

        <div class="px-4 py-1 my-4">
          <%= f.hidden_field :answer, id: "answer" %>
          <div class="editor readonly" data-target="answer"></div>
        </div>

        <div class="px-4 py-1 my-4">
          <div class="">
            <div id="run-result" class="block min-h-2 px-3 py-2"><%= @result %></div>
          </div>
        </div>

      </div>
    
      <div class="shadow border rounded my-5">

        <div class="mg-0 leading-loose border-b">
          <%= f.label :test_code, 'Test', class: 'block w-100 px-5 text-gray-600'%>
        </div>

        <div class="px-4 py-1 my-4">
          <%= f.hidden_field :test_code, id: "test_code" %>
          <div id="section-test-code">
            <section>
              <%= f.label :test_code, '測試資料', class: 'uppercase tracking-wide text-gray-700 text-m font-bold mt-5 mb-3'%>
            </section>
            
            <% if @card.test_code %>
              <% @card.test_code.each do |test_code| %>
                <%= f.label :test_code, id: "test_code", class: 'block border', value: test_code%>
              <% end %>
            <% end %>
          </div>
        </div>
        
      </div>

      <div class="my-5">
        <span class="block">
          <%= link_to '編輯', edit_board_card_path(@board.id, @card.id),  class: 'w-2 bg-orange-500 hover:bg-orange-700 text-white py-1 px-2 rounded mr-1' %>
        </span>
      </div>

    <% end %>
</div>

app/views/cards/_content_subject.html.erb
<div class="mg-0 pb-4">
  <h1 class="font-semibold text-4xl text-gray-700">
    <span class="mr-3 -m-10"><%= @card.order %></span><span class="text-3xl mb-3 font-semibold"><%= @card.title %></span>
  </h1>

  <p class="mt-6 -ml-16 -mb-12">
      <span class="mr-4 bg-transparent text-blue-700 font-semibold py-1 px-2 border border-blue-500 rounded">
        <%= @card.level %>
      </span>
  </p>
  <section id="card-description" class="lead text-l text-gray-700 mb-4">
    <%= @card.description %>
  </section>
  <p class="my-2">
    <% @card.tags&.each do |tag| %>
        <span class="inline-block bg-gray-200 px-3 py-0 text-sm text-gray-700 mr-2">
          <%= tag %>
        </span>    
    <% end %>
  </p>
</div>

app/views/cards/_data_hint.html.erb
<p class="hint-item"">
  <span class="numHint"><%= num %></span>
  <input name="card[hints][]" value="<%= hint %>">
  <span id="btn-del-hint">
    <i class="fa fa-minus-circle hover:text-red-700 text-red-500 rounded-full text-2xl"></i>
  </span>
  <% num = num + 1 %>
</p>

app/views/cards/_data_test_item.html.erb
<p class="test-item flex">
  <span class="numTestCode"><%= num %></span>
  <input name="card[test_code][]" class="w-full" value="<%= test_code %>">
  <span id="btn-del-test-code">
    <i class="fa fa-minus-circle hover:text-red-700 text-red-500 rounded-full text-2xl"></i>
  </span>
  <% num = num + 1 %>
</p>

app/views/cards/_nav_cards_list.html.erb
 <div id="part-cards-list">
  <div class="">

      <% @board.cards.order(:order).each do |card|%>
      
        <section class="one-card flex w-100 relative">
          <% if card.id %>
            <%= link_to(board_card_path(@board.id, card.id), 
                    :class => "#{'active' if card.id == nowCard} flex pr-16 border-b block w-full text-blue-700 hover:text-blue-500 hover:bg-gray-200 py-4 py-3") do %>
              <span class="arrow inline-block w-4 px-2 mx-2 -ml-8 absolute">
                <i class="fa fa fa-chevron-right text-blue-700 hover:text-blue-500 hover:bg-gray-200"></i>
              </span>

              <span class="border-r min-w-8 inline-block font-semibold mr-2 text-blue-500 text-center"><%= card.order %></span>
              <span class="inline-block"><%= card.title %></span>
              
            <% end %>

            <% if user_authority ==  "author" %>

              <div class="part-btns hover absolute my-4 pr-2 right-0 <%="not-allowed" if card.has_records? %>">
                
                <%= link_to(edit_board_card_path(@board.id, card.id), 
                            :class => 'w-2 text-gray-500 hover:text-gray-700 text-white py-1 rounded mr-1') do %>
                  <i class="btn-edit fa fa-pencil  text-2xl"></i>
                <% end %>

                <%= link_to(board_card_path(@board.id, card.id),method: 'delete',data: {confirm: 'Are you sure ?!'}, 
                            :class => 'w-2 text-gray-500 hover:text-gray-700 text-white py-1 rounded mr-1') do %>
                  <i class="btn-del fa fa-times text-2xl"></i>
                <% end %>

              </div>

            <% else %>

              <div>
              <!--
                <div class="absolute my-4 pr-4 right-0">
                    <i class="fa fa-file-o text-blue-700 hover:text-blue-500 hover:bg-gray-200"></i>
                </div>
              -->
              </div>

            <% end %>

          <% end %>

      </section>
    <% end %>
  </div>
</div>

app/views/cards/_tags_js.html.erb
      <option value="each">each</option>
      <option value="array">array</option>
      <option value="object">object</option>
      <option value="number">number</option>
      <option value="string">string</option>

app/views/cards/_tags_option.html.erb
<% @options.each do |tag|%>
<%= content_tag :option, tag, value: tag%>
<% end %>

app/views/cards/card_solved.html.erb
<span id="board-lang" class="hidden"><%= @board.editor_mode %></span>

<style>
  #btn-del-test-code{display:none;}
  input[name^="card[test_code]"]{
      disabled: true;
      pointer-events: none;
  }
</style>

<div id="page-show-solved" class="container-full">  
  
  <div class="flex w-full">
    <div id="cards-nav" class="w-1/3 m-0 border-r bg-white shadow shadow">
      <div id="part-borard-info" class="">
          <%= render "cards/banner_board_info" %>
      </div>
      <div id="part-cards-list" class="m-0">
        <%= render "cards/nav_cards_list",  nowCard: @card.id  %>
      </div>
    </div>
    <div id="part-card-content" class="w-2/3 m-0">
      <div class="flex-grow"">

        <div id="content-subject" class=" border rounded mb-8">
        
          <div class="content-body pr-10 pl-20 pb-8 pt-4 bg-white rounded-t border-t-4 border-blue-500 shadow-md">
          
            <div class="w-full mb-4">
              <%= render "cards/content_subject" %>


              <div class="border-t border-b py-4">
                <% if @card.hints %>
                  <p class="text-gray-600 text-m -ml-4 mb-3">
                    <span>提示(<%=@card.hints.length%>)</span>
                  </p>   
                  <ol class="list-decimal ml-4">
                    <% @card.hints.each do |hint| %>
                      <li class="hint"><%= hint %></li>
                    <% end %>
                  </ol>
                <% else %>
                  <span class="text-gray-400 text-s">(暫無提示)</span>
                <% end %>
              </div>
          </div>
        </div>
      

        <div id="content-answer" class="shadow border rounded mb-8">

          <div class="content-body px-10 pb-8 pt-4 bg-white border-t-4 border-green-500 shadow-md">
          
            <div class="w-full mb-4">

              <div class="text-gray-600 text-m -ml-4 mb-3">
                <label for="record_code" class="block w-100 px-5 text-gray-600">作答</label>
                <% label :code, '作答', class: 'block w-100 px-5 text-gray-600'%>
              </div>
              <div class="px-4 py-1 my-4">
                <% hidden_field :code, id: "code" %>
                <input type="hidden" id="code" name="record[code]" value="<%= @record.code %>">
                <div solving class="editor readonly" data-target="code"></div>
              </div>

            </div>

            <div id="part-test-run">   

              <div class="flex w-full px-4 py-1 my-2 -mt-1">
                <section class="w1/2 m-auto mt-6">
                  <label for="test_code" class="uppercase tracking-wide text-gray-700 text-m font-bold mt-5 mb-3">
                    測試方法 → 執行結果
                  </label>
                </section>
              </div>

              <div class="flex w-full mb-4 px-6 test-code-cover">
                <div class="w-1/2">
                  <div id="section-test-code">
                    
                      <% num = 0 %>
                      <% @card.test_code.each do |test_code| %>
                        <% num = num + 1 %>
                        <%= render "cards/data_test_item", num: num ,test_code: test_code %>
                      <% end %>
                
                  </div>
                </div>

                <div class="w-1/2">
                  <div id="run-result" class="">
                    <% num = 1 %>
                    <% if @card.result %>
                      <% @card.result.try(:each) do |result| %>
                        <div id="result<%= num %>" class=""><%= result %></div>
                        <div class="editor-" data-target="result<%= num %>"></div>
                        <% num = num + 1 %>
                      <% end %>
                    <% end %>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
        <div id="content-answer" class="shadow border rounded mb-8">

          <div class="content-body px-10 pb-8 pt-4 bg-white rounded-b border-t-4 border-gray-500 shadow-md">

            <% if @solved_records.length > 1 %>
            
              <div id="content-otheranswer" class="shadow rounded mb-8">
                <p class="text-gray-600 text-m -ml-4 mb-3">
                  <span>看其他人的解</span>
                </p>   
              <div class="content-body">
                <div class="w-full m-0 flex flex-wrap">
                
                  <% @solved_records&.each do |record| %>
                    <% unless record.user == current_user %>
                      <div class="border w-full p-4 box-border">

                        <%= link_to profile_path(record.user) do %>
                          <%= email_account(record.user) %>
                        <% end %>

                        <%= link_to record_path(id: record.id), :class=> 'border-b py-2' do %>
                          <i class="fa fa-file-text-o" aria-hidden="true"></i>
                        <% end %>
                        <div class="editor-readonly whitespace-pre-line"><%= record.code %></div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div> 
  </div>
</div>

app/views/cards/card_solving.html.erb
<span id="board-lang" class="hidden"><%= @board.editor_mode %></span>

<style>
  #btn-del-test-code{display:none;}
  input[name^="card[test_code]"]{
      disabled: true;
      pointer-events: none;
  }
  
</style>

<%= form_with model: @record, url: solve_board_card_path, method: :patch, local: true do |f| %>

  <div id="page-show-solving" class="container-full">  
  <div class="flex w-full">
    <div id="cards-nav" class="hidden md:block lg:block  w-1/3 m-0 border-r bg-white shadow">
      <div id="part-borard-info" class="">
          <%= render "cards/banner_board_info" %>
      </div>
      <div id="part-cards-list" class="m-0">
        <%= render "cards/nav_cards_list",  nowCard: @card.id  %>
      </div>
    </div>
    <div id="part-card-content" class="w-full md:w-2/3 lg:w-2/3 m-0">
      <div class="flex-grow"">

        <div id="content-subject" class="rounded mb-8">
        
          <div class="content-body pr-10 pl-20 pb-8 pt-4 bg-white rounded-t border-t-4 border-blue-500 shadow-md">
          
            <div class="w-full mb-4">
              <%= render "cards/content_subject" %>


              <div class="border-t border-b py-4">
                <% if @card.hints %>
                  <p  id="btn-show-hints" class="text-gray-600 text-m -ml-4 mb-3">
                    <span>提示(<%=@card.hints.length%>)</span>
                    <span>   
                      <i class="fa fa-plus"></i>
                    </span>   
                    <ol class="list-decimal ml-4">
                      <% @card.hints.each do |hint| %>
                        <li class="hint hidden"><%= hint %></li>
                      <% end %>
                    </ol>
                  </p>
                <% else %>
                  <span class="text-gray-400 text-s">(暫無提示)</span>
                <% end %>
              </div>
          </div>
        </div>
      

        
        <div id="content-answer" class=" border rounded mb-8">

          <div class="content-body px-10 pb-8 pt-4 bg-white border-t-4 border-green-500 shadow-md my-8">
          
            <div class="w-full mb-4">

              <div class="text-gray-600 text-m -ml-4 mb-3">
                <label for="record_code" class="block w-100 px-5 text-gray-600">作答</label>
                <% label :code, '作答', class: 'block w-100 px-5 text-gray-600'%>
              </div>
              <div class="px-4 py-1 my-4">
                <%= f.hidden_field :code, id: "code" %>
                <div solving class="editor <%= "readonly opacity-50" if user_authority == "guest" %>" data-target="code"></div>

              <% if user_authority != "guest" %>
                <div class="flex w-full">
                    <%= f.submit 'Run',id: 'btn-card-submit', class: 'm-auto bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded my-5' %>
                </div>
              <% end %>

              </div>
            </div>

            <div id="part-test-run">

              <% if user_authority != "guest" %>
                
                <div class="flex w-full px-4 py-1 my-2 -mt-1">
                  <section class="w1/2 m-auto mt-6">
                    <%= f.label :test_code, '測試方法 → 執行結果 ', class: 'uppercase tracking-wide text-gray-700 text-m font-bold mt-5 mb-3'%>
                  </section>
                </div>

                <div class="flex w-full mb-4 test-code-cover">

                  <div class="w-1/2">
                    <div id="section-test-code">         
                      <% num = 0 %>
                      <% @test_code.each do |test_code| %>
                        <% num = num + 1 %>
                        <%= render "cards/data_test_item", num: num ,test_code: test_code %>
                      <% end %>
                    </div>
                  </div>
                  
                  <div class="w-1/2">
                    <div id="run-result" class="">
                      <% num = 1 %>
                      <% @result.try(:each) do |result| %>
                        <div id="result<%= num %>" class=""><%= result %></div>
                        <div class="editor-" data-target="result<%= num %>"></div>
                        <% num = num + 1 %>
                      <% end %>
                    </div>
                  </div>

                </div>
              <% end %>
            </div>
          </div>
        </div> 

        <div class="flex my-6 pt-5 ">
          <% if user_authority == "guest" %>
            <%= link_to "請登入後作答", new_user_registration_path, class:"m-auto bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded my-5" %>
          <% else %>
            <%= f.submit '送出', class: 'm-auto mr-0 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'  %>
          <% end %>
        <div>

      </div>

    </div>

<% end %>
  
  

app/views/cards/edit.html.erb
<%= form_with model: @card, url: board_card_path, method: :patch , local: true do |f| %>

  <div id="page-edit" class="container-full">

    <div class="flex w-full">
    
      <div id="cards-nav" class="w-1/3 m-0 border-r bg-white shadow">
        <div id="part-borard-info" class="">
            <%= render "cards/banner_board_info" %>
        </div>
        <div id="part-cards-list" class="m-0">
          <%= render "cards/nav_cards_list", nowCard: @card.id %>
        </div>
      </div>

      <div id="part-card-content" class="w-2/3 m-0">
        <div class="flex-grow"">
          <%= render 'form', model: @card, f: f  %>
        </div>
      </div>

    </div>

<% end %>

app/views/cards/show.html.erb
<h1>qmaker page</h1>