config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'home#index'
  
  resources :boards do
    collection do
      get :my
    end
    resources :cards do
      member do
        patch :solve 
        get :solve, to: 'cards#show'
      end
      resources :comments, only: [:create]
    end 
  end


  resources :profiles, only: [:show]
  resources :cards, only: [:index] ,to: 'cards#list'

  resources :cards, only: [:index], to: 'cards#list'

  resources :records, only: [:show]
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>{ CodeBoard }</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class= "font-sans leading-normal tracking-normal">

  <% if flash[:alert] %>
    <div class="bg-red-500">
      <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= flash[:alert] %></div>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="bg-green-500">
      <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= flash[:notice] %></div>
    </div>
  <% end %>
  <% flash.clear %>
  
  <nav id="nav" class="text-white flex items-center justify-between flex-wrap border-b border-gray-400 bg-maincolor-1">
    <div class="container sm:m-auto flex">
      <div class="flex-grow sm:flex-grow-0  flex items-center flex-no-shrink mr-10">
        <%= link_to "{ CodeBoard }", root_path, class:"text-white hover:no-underline link border-b-2 border-transparent hover:border-maincolor-3 text-xl tracking-tight font-semibold" %>
      </div>

      <div class="block sm:hidden">
        <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-white border-white hover:text-black hover:border-white">
          <svg class="fill-current h-3 w-3 text-white" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
      </div>

      <div id="nav-content" class="mt-10 -ml-4 w-full mx-0 px-4 hidden fixed z-10 bg-maincolor-1 sm:bg-maincolor-1 sm:mt-0 sm:relative sm:flex-grow sm:text-center sm:flex sm:items-center sm:w-auto sm: pt-6 sm:pt-0">
        <div class="sm:flex-grow">
          <ul class="list-reset sm:flex justify-start flex-1 items-center">
            <li class="mr-3">
              <%= link_to "解題", boards_path, class: "hover:no-underline block border-b-2 border-transparent hover:border-maincolor-3 mt-4 sm:inline-block sm:mt-0 sm:mr-4 mb-2 sm:mb-0 link" %>
            </li>
            <li class="mr-3">
              <%= link_to "出題", my_boards_path, class: "hover:no-underline block  border-b-2 border-transparent hover:border-maincolor-3 mt-4 sm:inline-block sm:mt-0 sm:mr-4 mb-2 sm:mb-0 link" %>
            </li>
          </ul> 
        </div>
        
        <div class="w-full block sm:flex sm:flex-row sm:flex-1 mt-2 sm:mt-0 text-center sm:text-left sm:justify-end items-center">
          <% if user_signed_in? %>
            <div id="nav-user-img">
              <%= link_to profile_path(current_user.id), :title => current_user.email do %>
                <%= avatar_image_tag(current_user)  %>
              <% end %>
            </div>

            <%= link_to "登出", destroy_user_session_path, method: :delete, class:"btn mb-2 lg:mr-2 lg:mb-0 block rounded text-white border-white-600" %>
            
          <% else %>
            <%= link_to "登入", new_user_session_path, class:"btn mb-2 sm:mr-2 sm:mb-0 block rounded text-text border-text hover:text-white hover:border-white" %>
            <%= link_to "註冊", new_user_registration_path, class:" btn mb-2 sm:mr-2 sm:mb-0 block rounded text-text border-text hover:text-white hover:border-white" %>
          <% end %>
        </div>  
      </div>  
    </div>    
  </nav>

  <script>
    //Javascript to toggle the menu
    document.getElementById('nav-toggle').onclick = function(){
      document.getElementById("nav-content").classList.toggle("hidden");
    }
  </script>

  <main class=" <%= "bg-white" if current_path_last_string == nil %>" >
    <div class="container lg m-auto px-2">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </main>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.9/ace.js"></script>
  <script src="https://rawgithub.com/ajaxorg/ace-builds/master/src/ext-emmet.js"></script>
  <script src="https://rawgithub.com/nightwing/emmet-core/master/emmet.js"></script>

  </body>

</html>